### ISSUE TITLE
jiminyConfig.cmake recognizing 2.7 instead of specific python3 version

### ISSUE THREAD

**Issue by vcparedesc** [duburcqa/jiminy#391]
Hello,

We are compiling the example in pip_extension on a machine with Ubuntu 16.04 that has several python versions (2.7,  3.6 and 3.8). Whenever we try to run cmake we get that the detected Python version is 2.7 
![image](https://user-images.githubusercontent.com/1549925/128291800-10806916-0614-4798-8d5e-28aef82942c1.png)

When we modify "python" to "python3" in the file jiminyConfig.cmake, we are able to compile the example, with detected python version 3.8.

However, when we use update-alternatives to set the active python version to 3.6, jiminyConfig.cmake still detects 3.8 with the modification, or 2.7 otherwise. 

We need to use python3.6 because pinocchio is provided for py36 for Ubuntu 16.04. Is there some modification we can do to jiminyConfig.cmake to specify the python version or location we need? (3.6)

Thanks :)

**Comment by duburcqa** [comment]
Try to specify `PYTHON_EXECUTABLE="/usr/bin/python3.6"` in cmake command (or just `PYTHON_REQUIRED_VERSION="3.6"`, but not recommended for `cmake < 3.12.4`):

```
cmake "$RootDir/examples/pip_extension" -DCMAKE_INSTALL_PREFIX="$InstallDir" \
      -DPYTHON_EXECUTABLE="/usr/bin/python3.6" -DCMAKE_BUILD_TYPE="Release"
```

Otherwise by default it will rely on cmake to detect python, and apparently for some reason specifying it using `update-alternatives` if not enough :/

It should be pretty well tested so I would be surprised if it does not work out-of-the-box :)

**Comment by vcparedesc** [comment]
We were using update-alternatives, but somehow it got the python versions mixed up. Using -DPYTHON_EXECUTABLE="/usr/bin/python3.6" solved the problem and we could compile the code. Thanks!
